export const LANGS = [
  { code: "ko", name: "한국어" },
  { code: "en", name: "English" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "it", name: "Italiano" },
  { code: "pt", name: "Português" }
];

export const T = {
  ko: {
    title: "무엇이 궁금하세요?",
    ph: "예: 절두산 순교성지",
    live: "실시간 연결됨",
    local: "테스트 모드 · 이 기기에만 저장",
    found: (n) => `답변 ${n}개`,
    none: "아직 등록된 답변이 없어요",
    tabFaq: "자주 묻는 질문 (FAQ)",
    tabQa: "질문하기 (Q&A)",
    qaDesc: "궁금한 내용을 남겨주시면 안내 데스크에서 확인 후 답변해 드립니다.",
    askPlaceholder: "질문할 내용을 입력해 주세요 (예: 셔틀버스 운행 시간)",
    emptyT: "찾는 답이 없나요?",
    emptyB: "직접 질문을 남겨주시면 담당자가 신속히 답변해 드립니다.",
    goToQaBtn: "Q&A로 직접 질문하기",
    allCategories: "전체",
    send: "질문 접수하기",
    sending: "접수 중…",
    sent: "질문이 성공적으로 접수되었습니다",
    hint: "문제가 생겼을 때는 운영진에게 문의해주세요",
    mine: "내가 보낸 질문",
    wait: "답변 대기 중",
    done: "답변 완료",
    lang: "언어 선택",
    recent: "실시간 답변 목록",
    preparing: "답변 준비 중",
    soon: "담당 부서에서 확인하고 있습니다. 확정되는 대로 여기에 올라옵니다.",
    adminTitle: "운영자 화면",
    enterCode: "접속 번호를 입력하세요",
    unlockBtn: "들어가기",
    wrongCode: "번호가 맞지 않습니다",
    emptyAnswerAlert: "답변 내용을 적어주세요",
    sentAnswerAlert: "답변을 보냈습니다",
    savedAlert: "저장했습니다",
    emptyFieldAlert: "질문과 답변을 모두 적어주세요",
    addedFaqAlert: "FAQ에 추가했습니다",
    wipeConfirm: "받은 질문을 모두 지웁니다. 되돌릴 수 없습니다.",
    wipedAlert: "모두 지웠습니다",
    networkError: "보내지 못했습니다. 네트워크를 확인하세요.",
    screenTitle: "방금 들어온 질문과 답변",
    screenEmpty: "아직 답변된 질문이 없습니다. QR을 스캔해 질문을 보내주세요."
  },
  en: {
    title: "What can we help with?",
    ph: "e.g. Jeoldusan Martyrs' Shrine",
    live: "Live",
    local: "Test mode · saved on this device only",
    found: (n) => `${n} answer${n === 1 ? "" : "s"}`,
    none: "No answers yet",
    tabFaq: "FAQ",
    tabQa: "Ask Q&A",
    qaDesc: "Ask any question and our info desk team will reply promptly.",
    askPlaceholder: "Type your question here (e.g. Shuttle bus schedule)",
    emptyT: "Nothing matches",
    emptyB: "Didn't find what you need? Ask the desk directly.",
    goToQaBtn: "Ask in Q&A",
    allCategories: "All",
    send: "Submit Question",
    sending: "Submitting…",
    sent: "Your question was received",
    hint: "If you encounter any issues, please contact the staff.",
    mine: "Your questions",
    wait: "Waiting for reply",
    done: "Answered",
    lang: "Choose a language",
    recent: "Recently Answered",
    preparing: "Answer coming",
    soon: "The organising team is confirming this. The answer will appear here.",
    adminTitle: "Admin Panel",
    enterCode: "Please enter the passcode",
    unlockBtn: "Enter",
    wrongCode: "Passcode is incorrect",
    emptyAnswerAlert: "Please write an answer",
    sentAnswerAlert: "Answer sent",
    savedAlert: "Saved successfully",
    emptyFieldAlert: "Please fill in both question and answer",
    addedFaqAlert: "Added to FAQ",
    wipeConfirm: "Delete all questions? This cannot be undone.",
    wipedAlert: "All questions deleted",
    networkError: "Failed to send. Please check your network.",
    screenTitle: "Recently Answered Questions",
    screenEmpty: "No answered questions yet. Scan the QR code to ask."
  },
  es: {
    title: "¿En qué podemos ayudarte?",
    ph: "ej. Santuario de Jeoldusan",
    live: "En directo",
    local: "Modo de prueba · solo en este dispositivo",
    found: (n) => `${n} respuesta${n === 1 ? "" : "s"}`,
    none: "Aún no hay respuestas",
    tabFaq: "FAQ",
    tabQa: "Preguntas (Q&A)",
    qaDesc: "Haz cualquier pregunta y nuestro equipo te responderá.",
    askPlaceholder: "Escribe tu pregunta aquí (ej. Horario de autobuses)",
    emptyT: "No hay coincidencias",
    emptyB: "¿No encontraste lo que buscabas? Pregunta directamente.",
    goToQaBtn: "Preguntar en Q&A",
    allCategories: "Todos",
    send: "Enviar pregunta",
    sending: "Enviando…",
    sent: "Hemos recibido tu pregunta",
    hint: "Si tienes algún problema, por favor contacta al personal organizador.",
    mine: "Tus preguntas",
    wait: "Esperando respuesta",
    done: "Respondida",
    lang: "Elige un idioma",
    recent: "Respondidas ahora",
    preparing: "Respuesta en camino",
    soon: "El equipo organizador lo está confirmando. La respuesta aparecerá aquí.",
    adminTitle: "Panel de administración",
    enterCode: "Introduce el código de acceso",
    unlockBtn: "Entrar",
    wrongCode: "El código no es correcto",
    emptyAnswerAlert: "Por favor, escribe una respuesta",
    sentAnswerAlert: "Respuesta enviada",
    savedAlert: "Guardado correctamente",
    emptyFieldAlert: "Por favor escribe la pregunta y la respuesta",
    addedFaqAlert: "Añadido a FAQ",
    wipeConfirm: "¿Eliminar todas las preguntas? No se puede deshacer.",
    wipedAlert: "Todas las preguntas eliminadas",
    networkError: "Error al enviar. Comprueba tu conexión.",
    screenTitle: "Preguntas y respuestas recientes",
    screenEmpty: "Aún no hay preguntas respondidas. Escanea el código QR para preguntar."
  },
  fr: {
    title: "Comment pouvons-nous aider ?",
    ph: "ex. Sanctuaire de Jeoldusan",
    live: "En direct",
    local: "Mode test · enregistré sur cet appareil",
    found: (n) => `${n} réponse${n === 1 ? "" : "s"}`,
    none: "Pas encore de réponses",
    tabFaq: "FAQ",
    tabQa: "Poser (Q&A)",
    qaDesc: "Posez votre question, l'équipe d'accueil vous répondra rapidement.",
    askPlaceholder: "Saisissez votre question ici (ex. Horaires des navettes)",
    emptyT: "Aucun résultat",
    emptyB: "Pas de réponse ? Posez votre question directement.",
    goToQaBtn: "Poser dans le Q&A",
    allCategories: "Tous",
    send: "Envoyer la question",
    sending: "Envoi…",
    sent: "Votre question est bien reçue",
    hint: "En cas de problème, veuillez contacter l'équipe d'organisation.",
    mine: "Vos questions",
    wait: "En attente de réponse",
    done: "Répondu",
    lang: "Choisir la langue",
    recent: "Réponses récentes",
    preparing: "Réponse à venir",
    soon: "L'équipe d'organisation vérifie ce point. La réponse s'affichera ici.",
    adminTitle: "Panneau d'administration",
    enterCode: "Entrez le code d'accès",
    unlockBtn: "Entrer",
    wrongCode: "Code incorrect",
    emptyAnswerAlert: "Veuillez saisir une réponse",
    sentAnswerAlert: "Réponse envoyée",
    savedAlert: "Enregistré avec succès",
    emptyFieldAlert: "Veuillez remplir la question et la réponse",
    addedFaqAlert: "Ajouté aux FAQ",
    wipeConfirm: "Supprimer toutes les questions ? Action irréversible.",
    wipedAlert: "Toutes les questions supprimées",
    networkError: "Échec de l'envoi. Vérifiez votre connexion.",
    screenTitle: "Questions et réponses récentes",
    screenEmpty: "Pas encore de réponses. Scannez le code QR pour poser une question."
  },
  it: {
    title: "Come possiamo aiutarti?",
    ph: "es. Santuario di Jeoldusan",
    live: "In diretta",
    local: "Modalità test · salvato solo su questo dispositivo",
    found: (n) => `${n} rispost${n === 1 ? "a" : "e"}`,
    none: "Ancora nessuna risposta",
    tabFaq: "FAQ",
    tabQa: "Domande (Q&A)",
    qaDesc: "Fai qualsiasi domanda e il nostro staff ti risponderà subito.",
    askPlaceholder: "Scrivi la tua domanda qui (es. Orario delle navette)",
    emptyT: "Nessun risultato",
    emptyB: "Non hai trovato risposta? Fai una domanda diretta.",
    goToQaBtn: "Fai una domanda in Q&A",
    allCategories: "Tutti",
    send: "Invia domanda",
    sending: "Invio…",
    sent: "Domanda ricevuta",
    hint: "In caso di problemi, si prega di contattare lo staff.",
    mine: "Le tue domande",
    wait: "In attesa di risposta",
    done: "Risposta data",
    lang: "Scegli la lingua",
    recent: "Appena risposte",
    preparing: "Risposta in arrivo",
    soon: "Il comitato organizzatore sta verificando. La risposta comparirà qui.",
    adminTitle: "Pannello di amministrazione",
    enterCode: "Inserisci il codice di accesso",
    unlockBtn: "Entra",
    wrongCode: "Codice errato",
    emptyAnswerAlert: "Inserisci una risposta",
    sentAnswerAlert: "Risposta inviata",
    savedAlert: "Salvato con successo",
    emptyFieldAlert: "Compila sia la domanda che la risposta",
    addedFaqAlert: "Aggiunto alle FAQ",
    wipeConfirm: "Cancellare tutte le domande? Azione irreversibile.",
    wipedAlert: "Tutte le domande eliminate",
    networkError: "Invio non riuscito. Controlla la connessione.",
    screenTitle: "Domande e risposte recenti",
    screenEmpty: "Ancora nessuna risposta. Scansiona il codice QR per fare una domanda."
  },
  pt: {
    title: "Como podemos ajudar?",
    ph: "ex. Santuário de Jeoldusan",
    live: "Ao vivo",
    local: "Modo de teste · guardado só neste aparelho",
    found: (n) => `${n} respost${n === 1 ? "a" : "as"}`,
    none: "Ainda sem respostas",
    tabFaq: "FAQ",
    tabQa: "Perguntas (Q&A)",
    qaDesc: "Faça sua pergunta e a nossa equipe responderá em breve.",
    askPlaceholder: "Digite sua pergunta aqui (ex. Horários do translado)",
    emptyT: "Nada encontrado",
    emptyB: "Não encontrou o que procura? Pergunte diretamente.",
    goToQaBtn: "Perguntar no Q&A",
    allCategories: "Todos",
    send: "Enviar pergunta",
    sending: "A enviar…",
    sent: "Pergunta recebida",
    hint: "Em caso de problemas, entre em contato com a equipe organizadora.",
    mine: "As suas perguntas",
    wait: "À espera de resposta",
    done: "Respondida",
    lang: "Escolher idioma",
    recent: "Respondidas agora",
    preparing: "Resposta a caminho",
    soon: "A equipa organizadora está a confirmar. A resposta aparecerá aqui.",
    adminTitle: "Painel de administração",
    enterCode: "Digite o código de acesso",
    unlockBtn: "Entrar",
    wrongCode: "Código incorreto",
    emptyAnswerAlert: "Por favor, escreva uma resposta",
    sentAnswerAlert: "Resposta enviada",
    savedAlert: "Salvo com sucesso",
    emptyFieldAlert: "Por favor, preencha a pergunta e a resposta",
    addedFaqAlert: "Adicionado às FAQ",
    wipeConfirm: "Excluir todas as perguntas? Esta ação não pode ser desfeita.",
    wipedAlert: "Todas as perguntas foram excluídas",
    networkError: "Falha no envio. Verifique sua conexão.",
    screenTitle: "Perguntas e respostas recentes",
    screenEmpty: "Ainda não há perguntas respondidas. Leia o código QR para perguntar."
  }
};
